Repository YAPP-Github/Piece-Android, pull requests merged in 2024-12, with the labels that each got.

#2 #1 - 프로젝트 초기 세팅
  .DS_Store
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  .gitignore
  app/build.gradle.kts
  build-logic/.gitignore
  build-logic/build.gradle.kts
  build-logic/settings.gradle.kts
  build-logic/src/main/java/com/yapp/build/logic/Extension.kt
  build-logic/src/main/java/com/yapp/build/logic/HiltAndroid.kt
  build-logic/src/main/java/com/yapp/build/logic/HiltKotlin.kt
  build-logic/src/main/java/com/yapp/build/logic/KotlinAndroid.kt
  build-logic/src/main/java/com/yapp/build/logic/TestAndroid.kt
  build-logic/src/main/java/com/yapp/build/logic/TestKotlin.kt
  build-logic/src/main/java/com/yapp/build/logic/chaeum.android.application.gradle.kts
  build-logic/src/main/java/com/yapp/build/logic/chaeum.android.compose.gradle.kts
  build-logic/src/main/java/com/yapp/build/logic/chaeum.android.feature.gradle.kts
  build-logic/src/main/java/com/yapp/build/logic/chaeum.android.library.gradle.kts
  build-logic/src/main/java/com/yapp/build/logic/chaeum.kotlin.library.gradle.kts
  build-logic/src/main/java/com/yapp/build/logic/configure/AndroidComposes.kt
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 리뷰 원해요🔥, ㅌㄱ태규 ☀️

#4 #3 - 기본 화면 전환 구현
  app/build.gradle.kts
  app/src/androidTest/java/com/yapp/chaeum/ExampleInstrumentedTest.kt
  app/src/main/java/com/yapp/chaeum/MainActivity.kt
  app/src/main/java/com/yapp/chaeum/navigation/AppNavHost.kt
  app/src/main/java/com/yapp/chaeum/navigation/TopLevelDestinvation.kt
  app/src/main/java/com/yapp/chaeum/navigation/home/HomeNavigation.kt
  app/src/main/java/com/yapp/chaeum/ui/App.kt
  app/src/main/java/com/yapp/chaeum/ui/AppState.kt
  app/src/main/java/com/yapp/chaeum/ui/theme/Theme.kt
  app/src/test/java/com/yapp/chaeum/ExampleUnitTest.kt
  build-logic/src/main/java/com/yapp/build/logic/KotlinAndroid.kt
  build-logic/src/main/java/com/yapp/build/logic/chaeum.android.feature.gradle.kts
  feature/auth/.gitignore
  feature/auth/build.gradle.kts
  feature/auth/consumer-rules.pro
  feature/auth/proguard-rules.pro
  feature/auth/src/androidTest/java/com/example/auth/ExampleInstrumentedTest.kt
  feature/auth/src/main/AndroidManifest.xml
  feature/auth/src/main/java/com/example/auth/AuthScreen.kt
  feature/auth/src/main/java/com/example/auth/navigation/AuthNavigation.kt
  feature/auth/src/test/java/com/example/auth/ExampleUnitTest.kt
  feature/etc/.gitignore
  feature/etc/build.gradle.kts
  feature/etc/consumer-rules.pro
  feature/etc/proguard-rules.pro
  feature/etc/src/androidTest/java/com/example/etc/ExampleInstrumentedTest.kt
  feature/etc/src/main/AndroidManifest.xml
  feature/etc/src/main/java/com/example/etc/EtcScreen.kt
  feature/etc/src/main/java/com/example/etc/navigation/EtcNavigation.kt
  feature/etc/src/test/java/com/example/etc/ExampleUnitTest.kt
  feature/matching/.gitignore
  feature/matching/build.gradle.kts
  feature/matching/consumer-rules.pro
  feature/matching/proguard-rules.pro
  feature/matching/src/androidTest/java/com/example/matching/ExampleInstrumentedTest.kt
  feature/matching/src/main/AndroidManifest.xml
  feature/matching/src/main/java/com/example/matching/MatchingScreen.kt
  feature/matching/src/main/java/com/example/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/example/matching/navigation/MatchingNavigation.kt
  feature/matching/src/test/java/com/example/matching/ExampleUnitTest.kt
  feature/mypage/.gitignore
  feature/mypage/build.gradle.kts
  feature/mypage/consumer-rules.pro
  feature/mypage/proguard-rules.pro
  feature/mypage/src/androidTest/java/com/example/mypage/ExampleInstrumentedTest.kt
  feature/mypage/src/main/AndroidManifest.xml
  feature/mypage/src/main/java/com/example/mypage/MyPageScreen.kt
  feature/mypage/src/main/java/com/example/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/test/java/com/example/mypage/ExampleUnitTest.kt
  gradle/libs.versions.toml
  local.properties
  settings.gradle.kts
Labels: 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#7 [PIECE-46] Core 모듈 추가 및 클린 아키텍처에 맞게 의존성 연결, Navigation을 한 포인트에서 관리할 수 있도록 변경
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzle/piece/MainActivity.kt
  app/src/main/java/com/puzzle/piece/MainViewModel.kt
  app/src/main/java/com/puzzle/piece/PieceApplication.kt
  app/src/main/java/com/puzzle/piece/navigation/AppNavHost.kt
  app/src/main/java/com/puzzle/piece/navigation/TopLevelDestinvation.kt
  app/src/main/java/com/puzzle/piece/navigation/home/HomeNavigation.kt
  app/src/main/java/com/puzzle/piece/ui/App.kt
  app/src/main/java/com/puzzle/piece/ui/AppState.kt
  build-logic/build.gradle.kts
  build-logic/src/main/java/com/puzzle/build/logic/HiltAndroid.kt
  build-logic/src/main/java/com/puzzle/build/logic/piece.android.feature.gradle.kts
  build.gradle.kts
  core/data/.gitignore
  core/data/build.gradle.kts
  core/data/consumer-rules.pro
  core/data/proguard-rules.pro
  core/data/src/androidTest/java/com/puzzle/data/ExampleInstrumentedTest.kt
  core/data/src/main/AndroidManifest.xml
  core/data/src/test/java/com/puzzle/data/ExampleUnitTest.kt
  core/designsystem/.gitignore
  core/designsystem/build.gradle.kts
  core/designsystem/consumer-rules.pro
  core/designsystem/proguard-rules.pro
  core/designsystem/src/androidTest/java/com/puzzle/designsystem/ExampleInstrumentedTest.kt
  core/designsystem/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Color.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Theme.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Type.kt
  core/designsystem/src/test/java/com/puzzle/designsystem/ExampleUnitTest.kt
  core/domain/.gitignore
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/puzzle/domain/MyClass.kt
  core/navigation/.gitignore
  core/navigation/build.gradle.kts
  core/navigation/consumer-rules.pro
  core/navigation/proguard-rules.pro
  core/navigation/src/androidTest/java/com/puzzle/navigation/ExampleInstrumentedTest.kt
  core/navigation/src/main/AndroidManifest.xml
  core/navigation/src/main/java/com/puzzle/navigation/NavigationHelper.kt
  core/navigation/src/main/java/com/puzzle/navigation/Route.kt
  core/navigation/src/test/java/com/puzzle/navigation/ExampleUnitTest.kt
  core/network/.gitignore
  core/network/build.gradle.kts
  core/network/consumer-rules.pro
  core/network/proguard-rules.pro
  core/network/src/androidTest/java/com/puzzle/network/ExampleInstrumentedTest.kt
  core/network/src/main/AndroidManifest.xml
  core/network/src/test/java/com/puzzle/network/ExampleUnitTest.kt
  feature/auth/src/main/java/com/puzzle/auth/AuthScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/AuthViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/navigation/AuthNavigation.kt
  feature/etc/src/main/java/com/puzzle/etc/navigation/EtcNavigation.kt
  feature/matching/src/main/java/com/puzzle/matching/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/navigation/MatchingNavigation.kt
  feature/mypage/src/main/java/com/puzzle/mypage/navigation/MyPageNavigation.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 리팩토링 🧰, 머지 해도될듯염🌟, 잡다한 🗂️, ㅌㄱ태규 ☀️

#9 [PIECE-61] Mavericks 의존성 추가 및 Matching 모듈 Mavericks 적용
  app/build.gradle.kts
  app/src/main/java/com/puzzle/piece/PieceApplication.kt
  app/src/main/java/com/puzzle/piece/ViewModelsModule.kt
  build-logic/src/main/java/com/puzzle/build/logic/piece.android.feature.gradle.kts
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Typography.kt
  core/designsystem/src/main/res/font/decimal_book.otf
  feature/matching/src/main/java/com/puzzle/matching/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/contract/MatchingIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/contract/MatchingSideEffect.kt
  feature/matching/src/main/java/com/puzzle/matching/contract/MatchingState.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailSideEffect.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailState.kt
  feature/matching/src/main/java/com/puzzle/matching/navigation/MatchingNavigation.kt
  gradle/libs.versions.toml
Labels: 기능 ⚒️, 머지 해도될듯염🌟, 새롭게 알게 됨 📖, ㅌㄱ태규 ☀️

#10 [PIECE-54] 매칭 상세 페이지 화면 전환 구현
  app/src/main/java/com/puzzle/piece/ui/App.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailIntent.kt
  local.properties
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#12 [PC-105] 테스트용 카카오 로그인 추가
  .DS_Store
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/puzzle/piece/PieceApplication.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/puzzle/auth/AuthScreen.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#13 [PC-000] DesignSystem Typography 자간 제거
  .DS_Store
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Typography.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#11 [PC-92] Matching 화면 UI 구현
  build-logic/src/main/java/com/puzzle/build/logic/piece.android.feature.gradle.kts
  core/common-ui/.gitignore
  core/common-ui/build.gradle.kts
  core/common-ui/consumer-rules.pro
  core/common-ui/proguard-rules.pro
  core/common-ui/src/androidTest/java/com/puzzle/common/ui/ExampleInstrumentedTest.kt
  core/common-ui/src/main/AndroidManifest.xml
  core/common-ui/src/main/java/com/puzzle/common/ui/ModifierUtil.kt
  core/common-ui/src/test/java/com/puzzle/common/ui/ExampleUnitTest.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Color.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Typography.kt
  core/designsystem/src/main/res/drawable/ic_alarm.xml
  core/designsystem/src/main/res/drawable/ic_arrow_left.xml
  core/designsystem/src/main/res/drawable/ic_close.xml
  core/designsystem/src/main/res/font/decimal_book.otf
  feature/matching/src/main/java/com/puzzle/matching/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/contract/MatchingIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/res/drawable/ic_matching_loading.xml
  settings.gradle.kts
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, 새롭게 알게 됨 📖, ㅌㄱ태규 ☀️

#14 [PC-190] 매칭 상세 Basic Info Page 디자인 구현
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/res/drawable/ic_left_disable.xml
  core/designsystem/src/main/res/drawable/ic_more.xml
  core/designsystem/src/main/res/drawable/ic_right_able.xml
  core/designsystem/src/main/res/drawable/matchingdetail_bg.png
  core/domain/src/main/java/com/puzzle/domain/MyClass.kt
  core/domain/src/main/java/com/puzzle/domain/model/pick/ValuePickCard.kt
  core/domain/src/main/java/com/puzzle/domain/model/value/ValueTalkCard.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailState.kt
  feature/matching/src/main/res/values/strings.xml
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#16 [PC-185] Bottom Navigation Bar UI 구현
  app/build.gradle.kts
  app/src/main/java/com/puzzle/piece/navigation/AppNavHost.kt
  app/src/main/java/com/puzzle/piece/navigation/TopLevelDestinvation.kt
  app/src/main/java/com/puzzle/piece/ui/App.kt
  app/src/main/res/drawable/ic_matching.xml
  app/src/main/res/drawable/ic_profile.xml
  app/src/main/res/drawable/ic_setting.xml
  build-logic/src/main/java/com/puzzle/build/logic/configure/AndroidComposes.kt
  core/common-ui/src/main/java/com/puzzle/common/ui/InteractionSource.kt
  core/navigation/src/main/java/com/puzzle/navigation/Route.kt
  feature/etc/src/main/java/com/puzzle/etc/navigation/EtcNavigation.kt
  feature/matching/src/main/java/com/puzzle/matching/MatchingScreen.kt
  feature/setting/.gitignore
  feature/setting/build.gradle.kts
  feature/setting/consumer-rules.pro
  feature/setting/proguard-rules.pro
  feature/setting/src/androidTest/java/com/puzzle/setting/ExampleInstrumentedTest.kt
  feature/setting/src/main/AndroidManifest.xml
  feature/setting/src/main/java/com/puzzle/setting/SettingScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/navigation/SettingNavigation.kt
  feature/setting/src/test/java/com/puzzle/setting/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: UI/UX 🎨, 머지 해도될듯염🌟, 새롭게 알게 됨 📖, ㅌㄱ태규 ☀️

#15 [PC-207] 매칭 상세 보기 Value Talk Ui 구현
  app/src/main/java/com/puzzle/piece/MainActivity.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Typography.kt
  core/designsystem/src/main/res/drawable/ic_left_able.xml
  core/designsystem/src/main/res/drawable/ic_profile_image_temp.xml
  core/designsystem/src/main/res/drawable/ic_puzzle1.xml
  core/designsystem/src/main/res/drawable/ic_puzzle2.xml
  core/designsystem/src/main/res/drawable/ic_puzzle3.xml
  core/domain/src/main/java/com/puzzle/domain/model/pick/ValuePick.kt
  core/domain/src/main/java/com/puzzle/domain/model/value/ValueTalk.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailState.kt
  feature/matching/src/main/res/drawable/ic_matching_loading.xml
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙
