Repository YAPP-Github/Piece-Android, pull requests merged in 2025-01, with the labels that each got.

#19 [PC-225] 매칭 상세 상대방 프로필 확인 페이지 및 수락 Dialog 구현
  build-logic/src/main/java/com/puzzle/build/logic/KotlinAndroid.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Dialog.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/res/drawable/ic_image_default.xml
  feature/matching/build.gradle.kts
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/component/ValueTalkHeader.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/BasicInfoBody.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/ValuePickBody.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/ValueTalkBody.kt
  feature/matching/src/main/java/com/puzzle/matching/ui/DialogType.kt
  gradle/libs.versions.toml
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#20 [PC-217] 매칭 상세 value pick ui 구현
  core/common-ui/src/main/java/com/puzzle/common/ui/CollapsingHeaderNestedScrollConnection.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/res/drawable/ic_image_default.xml
  core/designsystem/src/main/res/drawable/ic_profile_image.xml
  core/designsystem/src/main/res/drawable/ic_question.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/matching/src/main/java/com/puzzle/matching/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/component/BasicInfoHeader.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/BasicInfoBody.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/ValuePickBody.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/ValueTalkBody.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#21 [PC-259] Network 기초 세팅
  .DS_Store
  .github/.DS_Store
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  .gitignore
  app/build.gradle.kts
  app/src/main/java/com/puzzle/piece/MainActivity.kt
  app/src/main/java/com/puzzle/piece/MainViewModel.kt
  app/src/main/java/com/puzzle/piece/ui/App.kt
  core/common-ui/src/main/java/com/puzzle/common/event/EventHelper.kt
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/puzzle/domain/model/auth/OAuthProvider.kt
  core/domain/src/main/java/com/puzzle/domain/model/error/ErrorHelper.kt
  core/domain/src/main/java/com/puzzle/domain/model/error/HttpResponseException.kt
  core/domain/src/main/java/com/puzzle/domain/model/matching/ValuePick.kt
  core/domain/src/main/java/com/puzzle/domain/model/matching/ValueTalk.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthRepository.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/puzzle/network/adapter/PieceCallAdapter.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/di/RetrofitModule.kt
  core/network/src/main/java/com/puzzle/network/model/auth/LoginOauthRequest.kt
  core/network/src/main/java/com/puzzle/network/model/auth/LoginOauthResponse.kt
  core/network/src/main/java/com/puzzle/network/model/auth/RequestAuthCodeRequest.kt
  core/network/src/main/java/com/puzzle/network/model/auth/RequestAuthCodeResponse.kt
  core/network/src/main/java/com/puzzle/network/model/auth/VerifyAuthCodeRequest.kt
  core/network/src/main/java/com/puzzle/network/model/auth/VerifyAuthCodeResponse.kt
  core/network/src/main/java/com/puzzle/network/source/AuthDataSource.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/ValuePickBody.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/content/ValueTalkBody.kt
  feature/matching/src/main/java/com/puzzle/matching/detail/contract/MatchingDetailState.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, 새롭게 알게 됨 📖, ㅌㄱ태규 ☀️

#23 [PC-000] Presentation 모듈 추가 및 책임 분리
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/res/drawable/ic_matching.xml
  core/designsystem/src/main/res/drawable/ic_profile.xml
  core/designsystem/src/main/res/drawable/ic_setting.xml
  presentation/.gitignore
  presentation/build.gradle.kts
  presentation/consumer-rules.pro
  presentation/proguard-rules.pro
  presentation/src/androidTest/java/com/puzzle/presentation/ExampleInstrumentedTest.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
  presentation/src/main/java/com/puzzle/presentation/di/ViewModelsModule.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/AppNavHost.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/TopLevelDestinvation.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
  presentation/src/main/java/com/puzzle/presentation/ui/AppState.kt
  presentation/src/test/java/com/puzzle/presentation/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 리팩토링 🧰, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#26 [PC-000] suspendRunCatching 추가
  core/common/src/main/java/com/puzzle/common/ResultUtil.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/puzzle/data/repository/TermsRepositoryImpl.kt
  core/network/src/main/java/com/puzzle/network/model/terms/LoadTermsResponse.kt
Labels: 리팩토링 🧰, 머지 해도될듯염🌟, 새롭게 알게 됨 📖, ㅌㄱ태규 ☀️

#27 [PC-300] 약관 디테일 화면 구현
  build-logic/src/main/java/com/puzzle/build/logic/KotlinAndroid.kt
  build-logic/src/main/java/com/puzzle/build/logic/configure/AndroidComposes.kt
  core/data/src/main/java/com/puzzle/data/repository/TermsRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/repository/TermsRepositoryImplTest.kt
  core/database/src/androidTest/java/com/puzzle/database/dao/TermsDaoTest.kt
  core/database/src/main/java/com/puzzle/database/dao/TermsDao.kt
  core/database/src/main/java/com/puzzle/database/model/terms/TermEntity.kt
  core/database/src/main/java/com/puzzle/database/source/term/LocalTermDataSource.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/WebView.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/model/terms/Term.kt
  core/navigation/build.gradle.kts
  core/network/src/main/java/com/puzzle/network/model/terms/LoadTermsResponse.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/registration/RegistrationDetailScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/registration/RegistrationScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/registration/RegistrationViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/registration/contract/RegistrationState.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/registration/ui/RegistrationDetailScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/common/component/BasicInfoHeader.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/common/constant/DialogType.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/common/ui/BasicInfoBody.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/common/ui/ValuePickBody.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/common/ui/ValueTalkBody.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/contract/MatchingDetailState.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#28 [PC-000] 약관 상세 화면 웹뷰가 렌더링 되기 이전 TopBar가 가려지던 것 해결
  app/build.gradle.kts
  build-logic/src/main/java/com/puzzle/build/logic/KotlinAndroid.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/registration/ui/RegistrationDetailScreen.kt
Labels: 머지 해도될듯염🌟, 잡다한 🗂️, ㅌㄱ태규 ☀️

#30 [PC-292] 로그인 화면, 번호 인증 화면 ui 구현
  build-logic/src/main/java/com/puzzle/build/logic/configure/AndroidComposes.kt
  core/common-ui/src/androidTest/java/com/puzzle/common/ui/ExampleInstrumentedTest.kt
  core/common-ui/src/main/AndroidManifest.xml
  core/common-ui/src/test/java/com/puzzle/common/ui/ExampleUnitTest.kt
  core/data/src/main/AndroidManifest.xml
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/AuthCodeRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/util/TimerManagerImpl.kt
  core/database/src/main/AndroidManifest.xml
  core/database/src/test/java/com/puzzle/database/ExampleUnitTest.kt
  core/designsystem/src/androidTest/java/com/puzzle/designsystem/ExampleInstrumentedTest.kt
  core/designsystem/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  core/designsystem/src/main/res/drawable/ic_alarm.xml
  core/designsystem/src/main/res/drawable/ic_arrow_left.xml
  core/designsystem/src/main/res/drawable/ic_arrow_right.xml
  core/designsystem/src/main/res/drawable/ic_check.xml
  core/designsystem/src/main/res/drawable/ic_close.xml
  core/designsystem/src/main/res/drawable/ic_google_login.xml
  core/designsystem/src/main/res/drawable/ic_kakao_login.xml
  core/designsystem/src/main/res/drawable/ic_left_able.xml
  core/designsystem/src/main/res/drawable/ic_left_disable.xml
  core/designsystem/src/main/res/drawable/ic_matching.xml
  core/designsystem/src/main/res/drawable/ic_more.xml
  core/designsystem/src/main/res/drawable/ic_profile.xml
  core/designsystem/src/main/res/drawable/ic_profile_image_temp.xml
  core/designsystem/src/main/res/drawable/ic_right_able.xml
  core/designsystem/src/main/res/drawable/ic_setting.xml
  core/designsystem/src/main/res/values/strings.xml
  core/designsystem/src/test/java/com/puzzle/designsystem/ExampleUnitTest.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthCodeRepository.kt
  core/domain/src/main/java/com/puzzle/domain/usecase/RequestAuthCodeUseCase.kt
  core/domain/src/main/java/com/puzzle/domain/usecase/VerifyAuthCodeUseCase.kt
  core/domain/src/main/java/com/puzzle/domain/util/TimerManager.kt
  core/domain/src/test/kotlin/com/puzzle/domain/RequestAuthCodeUseCaseTest.kt
  core/domain/src/test/kotlin/com/puzzle/domain/VerifyAuthCodeUseCaseTest.kt
  core/navigation/src/androidTest/java/com/puzzle/navigation/ExampleInstrumentedTest.kt
  core/navigation/src/main/AndroidManifest.xml
  core/navigation/src/test/java/com/puzzle/navigation/ExampleUnitTest.kt
  core/network/src/androidTest/java/com/puzzle/network/ExampleInstrumentedTest.kt
  core/network/src/main/AndroidManifest.xml
  core/network/src/main/java/com/puzzle/network/source/TermDataSource.kt
  core/network/src/test/java/com/puzzle/network/ExampleUnitTest.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerficationState.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationIntent.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationSideEffect.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationState.kt
  gradle/libs.versions.toml
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#32 [PC-254] 코루틴 유틸함수 추가 및 LoginScreen 불필요한 Spacer 제거
  core/common-ui/src/main/java/com/puzzle/common/ui/CoroutineUtil.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/contract/LoginSideEffect.kt
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
Labels: 리팩토링 🧰, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#31 [PC-347] 권한 얻는 기능 추가
  app/src/main/AndroidManifest.xml
  core/datasource/.gitignore
  core/datasource/build.gradle.kts
  core/datasource/consumer-rules.pro
  core/datasource/proguard-rules.pro
  core/datasource/src/androidTest/java/com/puzzle/datasource/ExampleInstrumentedTest.kt
  core/datasource/src/main/AndroidManifest.xml
  core/datasource/src/test/java/com/puzzle/datasource/ExampleUnitTest.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Toggle.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/contract/SignUpState.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/page/AccessRightsPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailRoute.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#33 [PC-362] 카카오 로그인 연동
  core/common-ui/src/main/java/com/puzzle/common/ui/CollapsingHeaderNestedScrollConnection.kt
  core/data/build.gradle.kts
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/repository/AuthRepositoryImplTest.kt
  core/datastore/.gitignore
  core/datastore/build.gradle.kts
  core/datastore/consumer-rules.pro
  core/datastore/proguard-rules.pro
  core/datastore/src/androidTest/java/com/puzzle/datastore/ExampleInstrumentedTest.kt
  core/datastore/src/main/AndroidManifest.xml
  core/datastore/src/main/java/com/puzzle/datastore/datasource/LocalTokenDataSource.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/LocalUserDataSource.kt
  core/datastore/src/main/java/com/puzzle/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/puzzle/datastore/util/DataStoreUtil.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthRepository.kt
  core/network/src/main/java/com/puzzle/network/model/auth/LoginOauthResponse.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/contract/LoginIntent.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/contract/LoginSideEffect.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/contract/LoginState.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  settings.gradle.kts
Labels: 기능 ⚒️, 머지 해도될듯염🌟, 테스트 📜, ㅌㄱ태규 ☀️

#35 [PC-255] 구글 로그인 연동
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/puzzle/auth/graph/login/GoogleApiContract.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/contract/LoginState.kt
  gradle/libs.versions.toml
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#34 [PC-363] 로그인 인증 리팩토링
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/AuthCodeRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/util/TimerManagerImpl.kt
  core/data/src/test/java/com/puzzle/data/repository/AuthRepositoryImplTest.kt
  core/datastore/src/androidTest/java/com/puzzle/datastore/ExampleInstrumentedTest.kt
  core/datastore/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TextFields.kt
  core/designsystem/src/main/res/drawable/ic_delete.xml
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/puzzle/domain/model/auth/Timer.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthCodeRepository.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthRepository.kt
  core/domain/src/main/java/com/puzzle/domain/usecase/RequestAuthCodeUseCase.kt
  core/domain/src/main/java/com/puzzle/domain/usecase/VerifyAuthCodeUseCase.kt
  core/domain/src/main/java/com/puzzle/domain/util/TimerManager.kt
  core/domain/src/test/kotlin/com/puzzle/domain/RequestAuthCodeUseCaseTest.kt
  core/domain/src/test/kotlin/com/puzzle/domain/TimerTest.kt
  core/domain/src/test/kotlin/com/puzzle/domain/VerifyAuthCodeUseCaseTest.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationIntent.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationSideEffect.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationState.kt
Labels: 리팩토링 🧰, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#36 [PC-396] 인증번호 요청 및 인증 API 연결
  core/data/src/main/java/com/puzzle/data/TokenManagerImpl.kt
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/repository/AuthRepositoryImplTest.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TextFields.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthRepository.kt
  core/network/src/main/java/com/puzzle/network/di/RetrofitModule.kt
  core/network/src/main/java/com/puzzle/network/interceptor/PieceInterceptor.kt
  core/network/src/main/java/com/puzzle/network/interceptor/TokenManager.kt
  core/network/src/main/java/com/puzzle/network/model/auth/VerifyAuthCodeResponse.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationIntent.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationSideEffect.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, 테스트 📜, ㅌㄱ태규 ☀️

#38 [PC-000] 애니메이션 추가 및 더미 데이터 추가
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Chip.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Dialog.kt
  core/designsystem/src/main/res/values/strings.xml
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailRoute.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/common/component/BasicInfoHeader.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/contract/MatchingDetailState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/BasicInfoPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValuePickPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValueTalkPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/AppNavHost.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#39 [PC-386] 세팅 ui 구현
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Radio.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TextFields.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/res/drawable/ic_radio_empty.xml
  core/designsystem/src/main/res/drawable/ic_radio_selected.xml
  core/designsystem/src/main/res/drawable/ic_refresh.xml
  core/designsystem/src/main/res/drawable/ic_time.xml
  core/designsystem/src/main/res/values/strings.xml
  core/navigation/src/main/java/com/puzzle/navigation/Route.kt
  feature/setting/src/main/java/com/puzzle/setting/SettingScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingIntent.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingSideEffect.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingState.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/WithdrawScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/WithdrawViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/contract/WithdrawIntent.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/contract/WithdrawSideEffect.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/contract/WithdrawState.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/page/ConfirmPage.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/page/ReasonPage.kt
  feature/setting/src/main/java/com/puzzle/setting/navigation/SettingNavigation.kt
  presentation/src/main/java/com/puzzle/presentation/di/ViewModelsModule.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/AppNavHost.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/TopLevelDestinvation.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#40 [PC-400] 프로필 생성 UI 구현
  core/common-ui/src/main/java/com/puzzle/common/ui/ModifierUtil.kt
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TextFields.kt
  core/designsystem/src/main/res/drawable/ic_delete_circle.xml
  core/designsystem/src/main/res/drawable/ic_plus.xml
  core/designsystem/src/main/res/drawable/ic_plus_circle.xml
  core/designsystem/src/main/res/drawable/ic_sns_call.xml
  core/designsystem/src/main/res/drawable/ic_sns_instagram.xml
  core/designsystem/src/main/res/drawable/ic_sns_kakao.xml
  core/designsystem/src/main/res/drawable/ic_sns_openchatting.xml
  core/domain/src/main/java/com/puzzle/domain/model/profile/Contact.kt
  core/network/src/main/java/com/puzzle/network/model/ApiResponse.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileIntent.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileState.kt
  feature/setting/src/main/java/com/puzzle/setting/SettingScreen.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#41 [PC-433] 프로필 메인 ui 구현
  core/designsystem/src/main/res/drawable/ic_alarm_black.xml
  core/designsystem/src/main/res/drawable/ic_arrow_right_black.xml
  core/designsystem/src/main/res/drawable/ic_question.xml
  core/designsystem/src/main/res/drawable/ic_talk.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/common/component/BasicInfoHeader.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/BasicInfoPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/home/ProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/contract/MainProfileIntent.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/contract/MainProfileSideEffect.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/contract/MainProfileState.kt
  feature/profile/src/main/java/com/puzzle/profile/navigation/ProfileNavigation.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
  presentation/src/main/java/com/puzzle/presentation/di/ViewModelsModule.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙
