Repository YAPP-Github/Piece-Android, pull requests merged in 2025-02, with the labels that each got.

#43 [PC-434] 가치관 talk ui 구현
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TextFields.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Typography.kt
  core/designsystem/src/main/res/drawable/ic_info.xml
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/model/matching/ValueTalk.kt
  core/navigation/src/main/java/com/puzzle/navigation/Route.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/contract/MainProfileIntent.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuepick/ValuePickScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuepick/ValuePickViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuepick/contract/ValuePickIntent.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuepick/contract/ValuePickSideEffect.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuepick/contract/ValuePickState.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/ValueTalkScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/ValueTalkViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/contract/ValueTalkIntent.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/contract/ValueTalkSideEffect.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/contract/ValueTalkState.kt
  feature/profile/src/main/java/com/puzzle/profile/navigation/ProfileNavigation.kt
  presentation/src/main/java/com/puzzle/presentation/di/ViewModelsModule.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/TopLevelDestinvation.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#45 [PC-452] 로그아웃 기능 추가
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/repository/AuthRepositoryImplTest.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthRepository.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingIntent.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, 테스트 📜, ㅌㄱ태규 ☀️

#46 [PC-476] 가치관 Pick, 가치관 Talk을 Splash 화면에서 동적으로 불러옵니다.
  app/src/main/AndroidManifest.xml
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/TermsRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/repository/MatchingRepositoryImplTest.kt
  core/data/src/test/java/com/puzzle/data/repository/TermsRepositoryImplTest.kt
  core/database/src/androidTest/java/com/puzzle/database/dao/ValuePicksDaoTest.kt
  core/database/src/androidTest/java/com/puzzle/database/dao/ValueTalksDaoTest.kt
  core/database/src/main/java/com/puzzle/database/PieceDatabase.kt
  core/database/src/main/java/com/puzzle/database/converter/PieceConverters.kt
  core/database/src/main/java/com/puzzle/database/dao/ValuePicksDao.kt
  core/database/src/main/java/com/puzzle/database/dao/ValueTalksDao.kt
  core/database/src/main/java/com/puzzle/database/di/DaosModule.kt
  core/database/src/main/java/com/puzzle/database/model/matching/ValuePickEntity.kt
  core/database/src/main/java/com/puzzle/database/model/matching/ValueTalkEntity.kt
  core/database/src/main/java/com/puzzle/database/model/terms/TermEntity.kt
  core/database/src/main/java/com/puzzle/database/source/LocalMatchingDataSource.kt
  core/database/src/main/java/com/puzzle/database/source/LocalTermDataSource.kt
  core/domain/src/main/java/com/puzzle/domain/model/matching/ValuePick.kt
  core/domain/src/main/java/com/puzzle/domain/model/matching/ValueTalk.kt
  core/domain/src/main/java/com/puzzle/domain/repository/MatchingRepository.kt
  core/domain/src/main/java/com/puzzle/domain/repository/TermsRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/matching/LoadValuePicksResponse.kt
  core/network/src/main/java/com/puzzle/network/model/matching/LoadValueTalksResponse.kt
  core/network/src/main/java/com/puzzle/network/source/MatchingDataSource.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/contract/MatchingDetailState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValuePickPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValueTalkPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/ValueTalkScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/contract/ValueTalkState.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, 테스트 📜, ㅌㄱ태규 ☀️

#48 [PC-000] Repository 테스트 코드 내 Mocking -> Fake로 변경
  core/data/src/main/java/com/puzzle/data/TokenManagerImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/TermsRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/UserRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/auth/FakeAuthDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/matching/FakeLocalMatchingDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/matching/FakeMatchingDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/term/FakeLocalTermDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/term/FakeTermDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/token/FakeLocalTokenDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/user/FakeLocalUserDataSource.kt
  core/data/src/test/java/com/puzzle/data/repository/AuthRepositoryImplTest.kt
  core/data/src/test/java/com/puzzle/data/repository/MatchingRepositoryImplTest.kt
  core/data/src/test/java/com/puzzle/data/repository/TermsRepositoryImplTest.kt
  core/database/src/main/java/com/puzzle/database/di/DatabaseModule.kt
  core/database/src/main/java/com/puzzle/database/source/LocalTermDataSource.kt
  core/database/src/main/java/com/puzzle/database/source/matching/LocalMatchingDataSource.kt
  core/database/src/main/java/com/puzzle/database/source/matching/LocalMatchingDataSourceImpl.kt
  core/database/src/main/java/com/puzzle/database/source/term/LocalTermDataSource.kt
  core/database/src/main/java/com/puzzle/database/source/term/LocalTermDataSourceImpl.kt
  core/database/src/test/java/com/puzzle/database/ExampleUnitTest.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/token/LocalTokenDataSource.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/token/LocalTokenDataSourceImpl.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/user/LocalUserDataSource.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/user/LocalUserDataSourceImpl.kt
  core/datastore/src/main/java/com/puzzle/datastore/di/DataStoreModule.kt
  core/network/src/main/java/com/puzzle/network/di/NetworkModule.kt
  core/network/src/main/java/com/puzzle/network/source/auth/AuthDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSourceImpl.kt
  core/network/src/main/java/com/puzzle/network/source/term/TermDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/term/TermDataSourceImpl.kt
  core/network/src/test/java/com/puzzle/network/ExampleUnitTest.kt
Labels: 리팩토링 🧰, 머지 해도될듯염🌟, 새롭게 알게 됨 📖, 테스트 📜, ㅌㄱ태규 ☀️

#49 [PC-389] 약관 API 연동 및 Toast UI 추가
  app/src/main/AndroidManifest.xml
  core/common-ui/src/main/java/com/puzzle/common/event/EventHelper.kt
  core/data/src/main/java/com/puzzle/data/repository/TermsRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/term/FakeTermDataSource.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/SnackBar.kt
  core/designsystem/src/main/res/drawable/ic_toast_matching.xml
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/repository/TermsRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/terms/AgreeTermsRequest.kt
  core/network/src/main/java/com/puzzle/network/source/term/TermDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/term/TermDataSourceImpl.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/contract/SignUpIntent.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/contract/SignUpSideEffect.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/contract/SignUpState.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/page/AccessRightsPage.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/page/TermPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
Labels: 기능 ⚒️, 리뷰 원해요🔥, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#50 [PC-513] 프로필 등록 API 추가
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/ProfileRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/matching/FakeMatchingDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/profile/FakeLocalProfileDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/profile/FakeProfileDataSource.kt
  core/data/src/test/java/com/puzzle/data/repository/AuthRepositoryImplTest.kt
  core/data/src/test/java/com/puzzle/data/repository/MatchingRepositoryImplTest.kt
  core/data/src/test/java/com/puzzle/data/repository/ProfileRepositoryImplTest.kt
  core/database/src/main/java/com/puzzle/database/di/DatabaseModule.kt
  core/database/src/main/java/com/puzzle/database/model/matching/ValuePickEntity.kt
  core/database/src/main/java/com/puzzle/database/model/matching/ValueTalkEntity.kt
  core/database/src/main/java/com/puzzle/database/source/profile/LocalProfileDataSource.kt
  core/database/src/main/java/com/puzzle/database/source/profile/LocalProfileDataSourceImpl.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/Contact.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/ValuePick.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/ValueTalk.kt
  core/domain/src/main/java/com/puzzle/domain/repository/MatchingRepository.kt
  core/domain/src/main/java/com/puzzle/domain/repository/ProfileRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/di/NetworkModule.kt
  core/network/src/main/java/com/puzzle/network/model/matching/LoadValuePicksResponse.kt
  core/network/src/main/java/com/puzzle/network/model/matching/LoadValueTalksResponse.kt
  core/network/src/main/java/com/puzzle/network/model/profile/GenerateProfileRequest.kt
  core/network/src/main/java/com/puzzle/network/model/profile/GenerateProfileResponse.kt
  core/network/src/main/java/com/puzzle/network/model/profile/UploadProfileImageRequest.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSourceImpl.kt
  core/network/src/main/java/com/puzzle/network/source/profile/ProfileDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/profile/ProfileDataSourceImpl.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/contract/MatchingDetailState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValuePickPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValueTalkPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/bottomsheet/ContactBottomSheet.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileState.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/ValueTalkScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/contract/ValueTalkState.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#51 [PC-538] 프로필 등록 이미지 기능 추가 및 API 연결
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/image/ImageResizer.kt
  core/data/src/main/java/com/puzzle/data/image/ImageResizerImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/ProfileRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/profile/FakeProfileDataSource.kt
  core/data/src/test/java/com/puzzle/data/repository/ProfileRepositoryImplTest.kt
  core/data/src/test/java/com/puzzle/data/spy/image/SpyImageResizer.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Dialog.kt
  core/domain/src/main/java/com/puzzle/domain/repository/ProfileRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/profile/UploadProfileRequest.kt
  core/network/src/main/java/com/puzzle/network/model/profile/UploadProfileResponse.kt
  core/network/src/main/java/com/puzzle/network/source/profile/ProfileDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/profile/ProfileDataSourceImpl.kt
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileIntent.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileState.kt
  gradle/libs.versions.toml
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#52 [PC-000] 이미지 에셋 나온 부분 이미지 적용!!
  core/designsystem/src/main/res/drawable/ic_avoid_acquaintances.xml
  core/designsystem/src/main/res/drawable/ic_leave.xml
  core/designsystem/src/main/res/drawable/ic_login_background.xml
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/page/AvoidAcquaintancesPage.kt
  feature/auth/src/main/java/com/puzzle/auth/navigation/AuthNavigation.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/WithdrawScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/page/ConfirmPage.kt
Labels: 잡다한 🗂️, ㅌㄱ태규 ☀️

#53 [PC-540] 온보딩 화면 구현
  core/designsystem/src/main/res/drawable/ic_onboarding_camera.xml
  core/designsystem/src/main/res/drawable/ic_onboarding_logo.xml
  core/designsystem/src/main/res/values/strings.xml
  core/navigation/src/main/java/com/puzzle/navigation/Route.kt
  feature/onboarding/.gitignore
  feature/onboarding/build.gradle.kts
  feature/onboarding/consumer-rules.pro
  feature/onboarding/proguard-rules.pro
  feature/onboarding/src/androidTest/java/com/puzzle/onboarding/ExampleInstrumentedTest.kt
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/puzzle/onboarding/OnboardingScreen.kt
  feature/onboarding/src/main/java/com/puzzle/onboarding/OnboardingViewModel.kt
  feature/onboarding/src/main/java/com/puzzle/onboarding/contract/OnboardingIntent.kt
  feature/onboarding/src/main/java/com/puzzle/onboarding/contract/OnboardingSideEffect.kt
  feature/onboarding/src/main/java/com/puzzle/onboarding/navigation/OnboardingNavigation.kt
  feature/onboarding/src/test/java/com/puzzle/onboarding/ExampleUnitTest.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/puzzle/presentation/navigation/AppNavHost.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
  settings.gradle.kts
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#54 [PC-541] 네트워크 모니터링 기능 추가
  app/src/main/AndroidManifest.xml
  core/designsystem/src/main/res/drawable/ic_network_error.xml
  gradle/libs.versions.toml
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
  presentation/src/main/java/com/puzzle/presentation/network/NetworkMonitor.kt
  presentation/src/main/java/com/puzzle/presentation/network/NetworkScreen.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#57 [PC-000] 토큰 health Check 로직 추가
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/auth/FakeAuthDataSource.kt
  core/domain/src/main/java/com/puzzle/domain/repository/AuthRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/interceptor/PieceInterceptor.kt
  core/network/src/main/java/com/puzzle/network/source/auth/AuthDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/auth/AuthDataSourceImpl.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#59 [PC-550] 지인 차단 기능 추가
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/designsystem/src/main/res/drawable/ic_avoid_acquaintances_check.xml
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/repository/MatchingRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/matching/BlockContactsRequest.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSource.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/contract/SignUpIntent.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/contract/SignUpState.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/page/AvoidAcquaintancesPage.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, 새롭게 알게 됨 📖, ㅌㄱ태규 ☀️

#58 [PC-000] 프로필 등록 Page Indicator 추가
  core/common/src/main/java/com/puzzle/common/ResultUtil.kt
  core/data/src/main/java/com/puzzle/data/repository/AuthRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/auth/FakeAuthDataSource.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Indicator.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/ApiResponse.kt
  core/network/src/main/java/com/puzzle/network/source/auth/AuthDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/auth/AuthDataSourceImpl.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/bottomsheet/JobBottomSheet.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/bottomsheet/LocationBottomSheet.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileState.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#62 [PC-551] 매칭 홈 분기 화면 UI 구현 및 API 연결
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/UserRepositoryImpl.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Typography.kt
  core/designsystem/src/main/res/drawable/ic_matching_check.xml
  core/designsystem/src/main/res/drawable/ic_matching_heart.xml
  core/designsystem/src/main/res/drawable/ic_user_pending_home.xml
  core/designsystem/src/main/res/font/wix_made_for_display_medium.otf
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/model/match/MatchInfo.kt
  core/domain/src/main/java/com/puzzle/domain/repository/MatchingRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetMatchInfoResponse.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSource.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/page/AvoidAcquaintancesPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/contract/MatchingDetailIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/contract/MatchingIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/contract/MatchingState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingLoadingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingPendingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingUserScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingWaitingScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#63 [PC-555] 매칭 상세화면 API 연결
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/matching/FakeLocalMatchingDataSource.kt
  core/data/src/test/java/com/puzzle/data/fake/source/matching/FakeMatchingDataSource.kt
  core/data/src/test/java/com/puzzle/data/repository/MatchingRepositoryImplTest.kt
  core/datastore/build.gradle.kts
  core/datastore/src/main/java/com/puzzle/datastore/datasource/matching/LocalMatchingDataSource.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/matching/LocalMatchingDataSourceImpl.kt
  core/datastore/src/main/java/com/puzzle/datastore/di/DataStoreModule.kt
  core/datastore/src/main/java/com/puzzle/datastore/util/DataStoreUtil.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Loading.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/OpponentProfile.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/OpponentValuePick.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/OpponentValueTalk.kt
  core/domain/src/main/java/com/puzzle/domain/repository/MatchingRepository.kt
  core/domain/src/main/java/com/puzzle/domain/usecase/matching/GetOpponentProfileUseCase.kt
  core/domain/src/test/kotlin/com/puzzle/domain/spy/repository/SpyMatchingRepository.kt
  core/domain/src/test/kotlin/com/puzzle/domain/usecase/matching/GetOpponentProfileUseCaseTest.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/di/NetworkModule.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetOpponentProfileBasicResponse.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetOpponentProfileImageResponse.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetOpponentValuePicksResponse.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetOpponentValueTalksResponse.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSourceImpl.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/contract/MatchingDetailState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/BasicInfoPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  gradle/libs.versions.toml
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#66 [PC-588] 에러 로깅 추가
  .github/ISSUE_TEMPLATE/.DS_Store
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  app/.gitignore
  app/build.gradle.kts
  build-logic/src/main/java/com/puzzle/build/logic/KotlinAndroid.kt
  build.gradle.kts
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/ErrorRepositoryImpl.kt
  core/domain/src/main/java/com/puzzle/domain/model/error/ErrorHelper.kt
  core/domain/src/main/java/com/puzzle/domain/repository/ErrorRepository.kt
  core/network/src/main/java/com/puzzle/network/di/NetworkModule.kt
  core/network/src/main/java/com/puzzle/network/source/error/DebugErrorDataSourceImpl.kt
  core/network/src/main/java/com/puzzle/network/source/error/ErrorDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/error/ErrorDataSourceImpl.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginViewModel.kt
  gradle/libs.versions.toml
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#67 [PC-596] 설정 페이지 웹뷰 및 API 연결
  .github/workflows/android_cd.yml
  .github/workflows/android_ci.yml
  core/data/src/main/java/com/puzzle/data/image/ImageResizerImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/UserRepositoryImpl.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/WebView.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/model/user/UserSetting.kt
  core/domain/src/main/java/com/puzzle/domain/repository/UserRepository.kt
  core/navigation/src/main/java/com/puzzle/navigation/Route.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/user/GetSettingInfoResponse.kt
  core/network/src/main/java/com/puzzle/network/model/user/UpdateSettingRequest.kt
  core/network/src/main/java/com/puzzle/network/source/user/UserDataSource.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingIntent.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingSideEffect.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingState.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/webview/WebViewScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/webview/WebViewViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/navigation/SettingNavigation.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/AppNavHost.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#69 [PC-606] 프로필 AI요약 페이지, 프로필 생성 완료 페이지 이미지 에셋 변경
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TopBar.kt
  core/designsystem/src/main/res/drawable/ic_profile_generate.xml
  core/designsystem/src/main/res/raw/anim_ai_summary.json
  core/designsystem/src/main/res/values/strings.xml
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileIntent.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileState.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/BasicProfilePage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/FinishPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/SummationPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/ValuePickPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/ValueTalkPage.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/AppNavHost.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#71 [PC-589] 매칭 상태 타이머 ui 적용
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/ProfileRepositoryImpl.kt
  core/data/src/main/java/com/puzzle/data/repository/UserRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/matching/FakeMatchingDataSource.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Check.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Toggle.kt
  core/designsystem/src/main/res/drawable/ic_avoid_acquaintances_check.xml
  core/designsystem/src/main/res/drawable/ic_block_matching_end.xml
  core/designsystem/src/main/res/drawable/ic_block_matching_no_more.xml
  core/designsystem/src/main/res/drawable/ic_block_notification.xml
  core/designsystem/src/main/res/drawable/ic_matching_check.xml
  core/designsystem/src/main/res/drawable/ic_matching_heart.xml
  core/designsystem/src/main/res/drawable/ic_network_error.xml
  core/designsystem/src/main/res/raw/anim_ai_summary.json
  core/domain/src/main/java/com/puzzle/domain/model/auth/Timer.kt
  core/domain/src/main/java/com/puzzle/domain/model/match/MatchInfo.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/MyProfile.kt
  core/domain/src/main/java/com/puzzle/domain/model/user/ProfileStatus.kt
  core/domain/src/main/java/com/puzzle/domain/model/user/RejectReason.kt
  core/domain/src/main/java/com/puzzle/domain/model/user/UserRole.kt
  core/domain/src/main/java/com/puzzle/domain/repository/MatchingRepository.kt
  core/domain/src/main/java/com/puzzle/domain/repository/UserRepository.kt
  core/domain/src/test/kotlin/com/puzzle/domain/spy/repository/SpyMatchingRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetContactsResponse.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetMatchInfoResponse.kt
  core/network/src/main/java/com/puzzle/network/model/matching/GetOpponentValuePicksResponse.kt
  core/network/src/main/java/com/puzzle/network/model/user/GetRejectReasonResponse.kt
  core/network/src/main/java/com/puzzle/network/source/auth/AuthDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSourceImpl.kt
  core/network/src/main/java/com/puzzle/network/source/user/UserDataSource.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/contract/VerificationState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/contact/ContactScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/contact/ContactViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValueTalkPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/contract/MatchingSideEffect.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/contract/MatchingState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingUserScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingWaitingScreen.kt
  feature/onboarding/src/androidTest/java/com/puzzle/onboarding/ExampleInstrumentedTest.kt
  feature/onboarding/src/test/java/com/puzzle/onboarding/ExampleUnitTest.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#74 [PC-000] 알림 기능을 RemoteConfig로 핸들링 합니다.
  core/data/src/main/java/com/puzzle/data/repository/ConfigureRepositoryImpl.kt
  core/domain/src/main/java/com/puzzle/domain/repository/ConfigureRepository.kt
  core/network/src/main/java/com/puzzle/network/source/configure/ConfigureDataSource.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/contract/MatchingState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingLoadingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingPendingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingUserScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingWaitingScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/contract/MainProfileState.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingState.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#72 [PC-614] 강제 업데이트 추가
  core/data/src/main/java/com/puzzle/data/di/DataModule.kt
  core/data/src/main/java/com/puzzle/data/repository/ConfigureRepositoryImpl.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/model/configure/ForceUpdate.kt
  core/domain/src/main/java/com/puzzle/domain/repository/ConfigureRepository.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/puzzle/network/di/NetworkModule.kt
  core/network/src/main/java/com/puzzle/network/model/configure/GetForceUpdateInfoResponse.kt
  core/network/src/main/java/com/puzzle/network/source/configure/ConfigureDataSource.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/contract/MatchingState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingLoadingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingPendingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingUserScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingWaitingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/ProfilePreviewViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/contract/MainProfileState.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/contract/SettingState.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
  presentation/src/main/java/com/puzzle/presentation/update/ForceUpdateDialog.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#75 [PC-000] preview 데이터 초기화, ui 갱신
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/matching/FakeMatchingDataSource.kt
  core/domain/src/main/java/com/puzzle/domain/repository/MatchingRepository.kt
  core/domain/src/test/kotlin/com/puzzle/domain/spy/repository/SpyMatchingRepository.kt
  core/network/src/main/java/com/puzzle/network/api/PieceApi.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSource.kt
  core/network/src/main/java/com/puzzle/network/source/matching/MatchingDataSourceImpl.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/contract/MatchingDetailIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/contract/MatchingIntent.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/ProfilePreviewScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/ProfilePreviewViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/contract/ProfilePreviewState.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/page/ValuePickPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/page/ValueTalkPage.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingViewModel.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅈㅎ찐혁 🌙

#77 [PC-000] 내부 테스트 QA 반영
  app/build.gradle.kts
  core/data/src/main/java/com/puzzle/data/image/ImageResizer.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TextFields.kt
  core/domain/src/main/java/com/puzzle/domain/model/match/MatchInfo.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValuePickPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValueTalkPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingUserScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/basic/BasicProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/BasicProfilePage.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#78 [PC-000]심사 중일 때 profile 탭 버튼 기능 막음
  core/data/src/main/java/com/puzzle/data/repository/UserRepositoryImpl.kt
  core/domain/src/main/java/com/puzzle/domain/repository/UserRepository.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: 머지 해도될듯염🌟, 픽스 👨‍🔧, ㅈㅎ찐혁 🌙

#79 [PC-000] 가치관 Talk PlaceHolder 추가, 매칭 로띠 추가 !!!
  core/data/src/main/java/com/puzzle/data/repository/MatchingRepositoryImpl.kt
  core/data/src/test/java/com/puzzle/data/fake/source/profile/FakeProfileDataSource.kt
  core/data/src/test/java/com/puzzle/data/repository/ProfileRepositoryImplTest.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/matching/LocalMatchingDataSource.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/matching/LocalMatchingDataSourceImpl.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/profile/LocalProfileDataSourceImpl.kt
  core/datastore/src/main/java/com/puzzle/datastore/datasource/term/LocalTermDataSourceImpl.kt
  core/designsystem/src/main/res/raw/anim_matching_success.json
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/puzzle/domain/model/profile/MyProfile.kt
  core/domain/src/main/java/com/puzzle/domain/model/profile/ValueTalkQuestion.kt
  core/domain/src/test/kotlin/com/puzzle/domain/usecase/profile/GetMyValueTalksUseCaseTest.kt
  core/network/src/main/java/com/puzzle/network/model/profile/GetMyValueTalksResponse.kt
  core/network/src/main/java/com/puzzle/network/model/profile/LoadValueTalkQuestionsResponse.kt
  feature/matching/build.gradle.kts
  feature/matching/src/main/java/com/puzzle/matching/graph/contact/ContactScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/contact/ContactViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/contact/contract/ContactState.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/basic/BasicProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/model/ValueTalkRegisterRO.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/BasicProfilePage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/ValuePickPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/ValueTalkPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/ValueTalkScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingScreen.kt
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#80 [PC-000] input validation 검사 추가, 미리 보기 뒤로가기 버튼 목적지 변경
  core/common/src/main/java/com/puzzle/common/TimeUtil.kt
  core/common/src/test/kotlin/com/puzzle/common/TimeUtilTest.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/TextFields.kt
  core/designsystem/src/main/res/drawable/ic_question_default.xml
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValuePickPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/ProfilePreviewViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/page/ValuePickPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/basic/BasicProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/basic/BasicProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/basic/contract/BasicProfileState.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/contract/RegisterProfileState.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/BasicProfilePage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/ValuePickPage.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuepick/ValuePickScreen.kt
Labels: 머지 해도될듯염🌟, 픽스 👨‍🔧, ㅈㅎ찐혁 🌙

#83 [PC-688] 프로필 생성 화면에서 뒤로가기 눌렀을 시 경고 Dialog 추가
  core/common-ui/src/main/java/com/puzzle/common/ui/ModifierUtil.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Button.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/Dialog.kt
  core/designsystem/src/main/res/drawable/ic_notice.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/matching/build.gradle.kts
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/page/MatchingUserScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/ProfilePreviewScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/page/BasicProfilePage.kt
  gradle/libs.versions.toml
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️

#82 [PC-683] SystemBar 색상 변경 로직 추가!!
  core/common-ui/src/main/java/com/puzzle/common/ui/Constant.kt
  core/common-ui/src/main/java/com/puzzle/common/ui/ModifierUtil.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/component/BottomSheet.kt
  core/designsystem/src/main/java/com/puzzle/designsystem/foundation/Theme.kt
  core/navigation/src/main/java/com/puzzle/navigation/NavigationHelper.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/login/LoginViewModel.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationScreen.kt
  feature/auth/src/main/java/com/puzzle/auth/graph/verification/VerificationViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/block/BlockViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/contact/ContactScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/contact/ContactViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/MatchingDetailViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/detail/page/ValuePickPage.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/ProfilePreviewScreen.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/preview/ProfilePreviewViewModel.kt
  feature/matching/src/main/java/com/puzzle/matching/graph/report/ReportViewModel.kt
  feature/onboarding/src/main/java/com/puzzle/onboarding/OnboardingScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/basic/BasicProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/main/MainProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileScreen.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/register/RegisterProfileViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuepick/ValuePickViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/ValueTalkViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/main/SettingViewModel.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/webview/WebViewScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/WithdrawScreen.kt
  feature/setting/src/main/java/com/puzzle/setting/graph/withdraw/WithdrawViewModel.kt
  presentation/src/main/java/com/puzzle/presentation/MainActivity.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
  presentation/src/main/java/com/puzzle/presentation/navigation/AppNavHost.kt
  presentation/src/main/java/com/puzzle/presentation/ui/App.kt
Labels: UI/UX 🎨, 기능 ⚒️, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️, ㅈㅎ찐혁 🌙

#84 [PC-692] AI 요약 도움 말풍선 추가
  core/designsystem/src/main/res/drawable/ic_ballon_point.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/matching/src/main/java/com/puzzle/matching/graph/main/MatchingViewModel.kt
  feature/profile/src/main/java/com/puzzle/profile/graph/valuetalk/ValueTalkScreen.kt
  presentation/src/main/java/com/puzzle/presentation/MainViewModel.kt
Labels: UI/UX 🎨, 머지 해도될듯염🌟, ㅌㄱ태규 ☀️
